# Generated by Django 5.0.2 on 2024-03-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='esal',
            new_name='salary',
        ),
    ]
