# Generated by Django 5.0.2 on 2024-03-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=16)),
                ('lname', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits_movie', models.CharField(max_length=32)),
                ('realsed_date', models.DateField()),
                ('box_office_collection', models.FloatField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_actor', to='testapp.actor')),
            ],
        ),
    ]
